# Generated by Django 4.0.4 on 2022-12-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
